#! /bin/bash

# Thx to https://gist.github.com/dsheiko/620c7b0dcfbda39ce959eab70c5b2077

version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/package.json | grep -m 1 '^\+.*version' | sed -s 's/[^A-Z0-9\.\-]//g'`

if [[ ! $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(\-[A-Z]+\.[0-9]+)?$ ]]; then
    echo -e "Skip tag: can not see new version in '$version'"
    exit 1
fi

git tag "v$version"
echo "Created a new tag, v$version"
