services:
  server:
    extends:
      file: compose.yaml
      service: server
    ports:
      - 5173:5173
    environment:
      NODE_ENV: production
    command: sh -c "npm run build && npm start"
  database:
    extends:
      file: compose.yaml
      service: database
