services:
  server:
    extends:
      file: compose.yaml
      service: server
    ports:
      - ${APP_PORT-5173}:${APP_PORT-5173}
    environment:
      NODE_ENV: production
    command: sh -c "npm run build && npm start"
  database:
    extends:
      file: compose.yaml
      service: database
